apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.appName }}
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"${{ values.appName }}:1.0","namespace":"${{ values.appName }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${{ values.appName }}\")].image","pause":"false"}]'
  labels:
    app: ${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  selector:
    matchLabels:
      app: ${{ values.appName }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: ${{ values.appName }}
        backstage.io/kubernetes-id: ${{ values.appName }}
    spec:
      volumes:
        - name: truststore
          secret:
            secretName: ${{ values.appName }}-truststore
            items:
              - key: truststore.jks
                path: clienttruststore.jks
            defaultMode: 420
      containers:
        - name: ${{ values.appName }}
          image: ${{ values.registryUrl }}/${{ values.appName }}/${{ values.appName }}:1.0
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
          volumeMounts:
            - name: truststore
              readOnly: true
              mountPath: /mnt/secrets