kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${{ values.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${{ values.appName }}-maven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi