apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  title: ${{ values.appName }}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.appName}}-bootstrap
    backstage.io/kubernetes-id: ${{values.appName}}
    janus-idp.io/tekton: ${{values.appName}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}

  links:
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces${{values.cluster}}/#https://${{values.host}}/${{values.destination}}?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - argocd
    - renovate
spec:
  type: service
  owner: ${{values.owner | dump}}
  system: workshop-camel-demo
  lifecycle: demo
