apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spring-boot-camel-on-openshift-template
  title: Create a Camel app for OpenShift
  description: Create a Camel app for OpenShift
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - openshift
    - argocd
spec:
  owner: shsingh
  system: microservices
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - component_id
        - repoBranchName
        - description
        - registryUrl
        - clusterDomain
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          maxLength: 23
        repoBranchName:
          title: Name of the branch in the Git repository
          type: string
          default: master
        description:
          title: Description
          type: string
          default: Spring Boot App Generated by Backstage
        registryUrl:
          title: Registry URL
          type: string
          default: image-registry.openshift-image-registry.svc:5000
        clusterDomain:
          title: OpenShift Cluster Domain
          type: string
          description: Your Cluster Domain Name apps.<cluster-id>.sandbox466.opentlc.com
    - title: Application repository Information
      required:
        - Repohost
      properties:
        Repohost:
          title: Repo Host
          type: string
          description: Your SCM host gitlab-gitlab.apps.<cluster-id>.sandbox466.opentlc.com
          default: gitlab-gitlab
            enum:
              - gitlab-gitlab
        owner:
            title: Repo Owner
            type: string
            description: Your SCM host organization/group
            default: development
            enum:
              - development

  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          appName: ${{ parameters.component_id }}
          owner: ${{ user.entity.metadata.name }}
          cluster: .${{ parameters.clusterDomain }}
          host: ${{ parameters.Repohost }}.${{ parameters.clusterDomain }}
          destination: ${{ parameters.owner }}/${{ parameters.component_id }}
          
    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.Repohost }}.${{ parameters.clusterDomain }}?owner=${{ parameters.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: configCodeTemplate
      name: Generating the Config Code Component
      action: fetch:template
      input:
        url: ./argocd
        values:
          appName: ${{ parameters.component_id }}
          host: ${{ parameters.Repohost }}.${{ parameters.clusterDomain }}
          registryUrl: ${{ parameters.registryUrl }}
          repoBranchName: ${{ parameters.repoBranchName }}
          cluster: .${{ parameters.clusterDomain }}
          git_owner: ${{ parameters.owner }}
          url: https://${{ parameters.Repohost }}.${{ parameters.clusterDomain }}/${{ parameters.owner }}/${{parameters.component_id}}.git
          repoUrl: https://${{ parameters.Repohost }}.${{ parameters.clusterDomain }}/${{ parameters.owner }}/${{parameters.component_id}}-config.git
        targetPath: ./gitops

    - id: publish-gitops
      name: Publishing to the Config Code Repository
      action: publish:gitlab
      input:
       repoUrl: "${{ parameters.Repohost }}.${{ parameters.clusterDomain }}?owner=${{ parameters.owner }}&repo=${{parameters.component_id}}-config"
       repoVisibility: public
       sourcePath: ./gitops

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.component_id }}-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://${{ parameters.Repohost }}.${{ parameters.clusterDomain }}/${{ parameters.owner }}/${{parameters.component_id}}-config.git
        path: 'argocd'

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}