apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${{ values.appName }}-init
  labels:
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  params:
    - name: git-revision
      value: master
  pipelineRef:
    name: ${{ values.appName }}
  serviceAccountName: pipeline
  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ${{ values.appName }}
    - name: mvn-dir
      persistentVolumeClaim:
        claimName: ${{ values.appName }}-maven