apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spring-boot-camel-on-openshift-template
  title: Create a Camel app for OpenShift
  description: Create a Camel app for OpenShift
  tags:
    - spring-boot
    - java
    - maven
    - tekton
    - openshift
    - argocd
spec:
  owner: shsingh
  system: microservices
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - component_id
        - repoBranchName
        - description
        - registryUrl
        - clusterDomain
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: my-quarkus-app
          ui:field: EntityNamePicker
          maxLength: 23
        repoBranchName:
          title: Name of the branch in the Git repository
          type: string
          default: master
        description:
          title: Description
          type: string
          default: Spring Boot App Generated by Backstage
        registryUrl:
          title: Registry URL
          type: string
          default: image-registry.openshift-image-registry.svc:5000
        clusterDomain:
          title: OpenShift Cluster Domain
          type: string
          default: apps.cluster-pxnsw.sandbox424.opentlc.com
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-pxnsw.sandbox424.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-pxnsw.sandbox424.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          appName: ${{ parameters.component_id }}
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.cluster-pxnsw.sandbox424.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          
    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: configCodeTemplate
      name: Generating the Config Code Component
      action: fetch:template
      input:
        url: ./argocd
        values:
          appName: ${{ parameters.component_id }}
          registryUrl: ${{ parameters.registryUrl }}
          repoBranchName: ${{ parameters.repoBranchName }}
          git_owner: ${{ parameters.repo.owner }}
          url: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}.git
          repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-config.git
        targetPath: ./gitops

    - id: publish-gitops
      name: Publishing to the Config Code Repository
      action: publish:gitlab
      input:
       repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}-config"
       repoVisibility: public
       sourcePath: ./gitops

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.component_id }}
        argoInstance: main
        namespace: ${{ parameters.component_id }}
        repoUrl: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-config.git
        path: 'manifests'

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}